server {

    server_name mep-projects.spereon.codes;

    root /var/www/mep-projects;
    index index.html;
    
    location = /github-webhook {
    proxy_pass http://127.0.0.1:9001/github-webhook;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /sw.js {
        add_header Cache-Control "no-cache";
    }

    location = /manifest.webmanifest {
        add_header Cache-Control "no-cache";
    }

    listen [::]:443 ssl; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/mep-projects.spereon.codes/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mep-projects.spereon.codes/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mep-projects.spereon.codes) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name mep-projects.spereon.codes;
    return 404; # managed by Certbot


}
